---
title: "DDS Project 1"
author: "CDHolmes"
date: "12/15/2021"
output: html_document
---

# Libraries
```{r}
library(ggplot2)
library(tidyverse)
library(magrittr)
library(maps)
library(dplyr)
library(rvest)
library(xml2)
library(scico)
```

# Variables
```{r}
beers <- read.csv(file.choose(), header = TRUE, encoding = "UTF-8")
breweries <- read.csv(file.choose(), header = TRUE, encoding = "UTF-8")
mapdata <- map_data("state")

## Add state abbreviation to mapdata
mapdata$State <- # nolint
    state.abb[match(mapdata$region, str_to_lower(state.name))]
mapdata[400, ] # checking random line for match
```

# Explore Datasets
```{r}
head(beers)
head(breweries)
head(mapdata)

dim(beers)
dim(breweries)
```

# Transform Data
```{r}
# Merge Breweries and Beers into one data frame
brew_beers <-
    left_join(beers, breweries, by = c("Brewery_id" = "Brew_ID")) %>%
    select(Name.x, Beer_ID, ABV, IBU, Brewery_id, Style, Ounces, Name.y, City,
        State) %>%
    filter(ABV > .001 | is.na(ABV)) %>%
    rename("beer_name" = "Name.x") %>%
    rename("brewery_name" =  "Name.y")

# Creating more strict style groups based on Beer Advocate dataframe
brew_beers_new <-
    brew_beers %>%
    filter(!is.na(Style)) %>%
    mutate(style_strict =
        ifelse(grepl("Stout", Style, ignore.case = TRUE), "Stout",
        ifelse(grepl("Ale|Kölsch|Altbier|Winter Warmer", Style,
            ignore.case = TRUE), "Ale",
        ifelse(grepl("IPA", Style, ignore.case = TRUE), "IPA",
        ifelse(grepl("Lager|Pilsener|Pilsner|Oktoberfest", Style,
            ignore.case = TRUE), "Lager",
        ifelse(grepl("Porter", Style, ignore.case = TRUE), "Porter",
        ifelse(grepl("Witbier|Hefeweizen", Style,
            ignore.case = TRUE), "Wheat Beer",
        ifelse(grepl("Bock", Style, ignore.case = TRUE), "Bock", "Other")))))))
    )
head(brew_beers_new)
view(brew_beers_new)
## Checking for major styles still in "Other"
brew_beers_new %>%
    group_by(style_strict) %>%
    summarize(count = n())

view(brew_beers_new %>%
    select(style_strict, Style, beer_name) %>%
    filter(style_strict == "Other") %>%
    group_by(Style) %>%
    summarize(count = n()))

# IBU Range
min_ibu <- min(brew_beers_new$IBU, na.rm = TRUE)
max_ibu <- max(brew_beers_new$IBU, na.rm = TRUE)
# ABV Range
min_abv <- min(brew_beers_new$ABV, na.rm = TRUE)
max_abv <- max(brew_beers_new$ABV, na.rm = TRUE)

# ABV and IBU category sequences
ibu_seq <- seq(min_ibu, max_ibu, (max_ibu - min_ibu) / 5)
abv_seq <- seq(min_abv, max_abv, (max_abv - min_abv) / 5)

# ABV Categories
brew_beers_new$abv_cat <-
    cut(brew_beers_new$ABV, breaks = abv_seq)
brew_beers_new$abv_cat_num <-
    cut(brew_beers_new$ABV, breaks = abv_seq, labels = c(1, 2, 3, 4, 5))
# IBU Categories
brew_beers_new$ibu_cat <-
    cut(brew_beers_new$IBU, breaks = ibu_seq)
brew_beers_new$ibu_cat_num <-
    cut(brew_beers_new$IBU, breaks = ibu_seq, labels = c(1, 2, 3, 4, 5))
```



# Ruberic Questions
```{r}
# Q1: How many breweries are present in each state?
# Dataframe of Brewereies by State
brew_beers_summary <- brew_beers_new %>%
    group_by(State) %>%
    summarize(count = n()) %>%
    as.data.frame()
brew_beers_summary$State <- str_remove_all(brew_beers_summary$State, " ") # nolint
head(brew_beers_summary)
view(brew_beers_summary)

# Bar Chart of Breweries by State
brew_beers_summary %>%
    ggplot(aes(x = reorder(State, -count), y = count, fill = State)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = count), stat = "identity", vjust = -1) +
    xlab("State") +
    ylab("Count") +
    ggtitle("Brewery Count by State") +
    theme_minimal() +
    theme(legend.position = "none")

# Q2: Merge beer data with the breweries data. Print the first 6 observations
# and the last six observations to check the merged file.  (RMD only, this does
# not need to be included in the presentation or the deck.)

## See Transform section for merge.

view(head(brew_beers, 6))
view(tail(brew_beers, 6))

# Q3: Address the missing values in each column.
colSums(is.na(brew_beers_new) | brew_beers_new == "")
## Missing values will be removed for ABV, IBU, and Styles as needed.

# Q4: Compute the median alcohol content and international bitterness unit for
# each state. Plot a bar chart to compare.
## Median ABV
median_state_abv <-
    brew_beers_new %>%
    filter(!is.na(ABV)) %>%
    group_by(State) %>%
    summarize(median_abv = median(ABV)) %>%
    as.data.frame()
median_state_abv

median_state_abv %>%
    ggplot(aes(
            x = reorder(State, -median_abv),
            y = median_abv * 100, fill = State)
    ) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = median_abv * 100),
        stat = "identity", vjust = -1, size = 3) +
    xlab("State") +
    ylab("Median ABV") +
    ggtitle("Median ABV by State") +
    theme_minimal() +
    theme(legend.position = "none")

## Median IBU
median_state_ibu <-
    brew_beers_new %>%
    filter(!is.na(IBU)) %>%
    group_by(State) %>%
    summarize(median_ibu = median(IBU)) %>%
    as.data.frame()
median_state_ibu

median_state_ibu %>%
    ggplot(aes(
            x = reorder(State, -median_ibu),
            y = median_ibu, fill = State
        )) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = median_ibu),
        stat = "identity", vjust = -1, size = 3) +
    xlab("State") +
    ylab("Median IBU") +
    ggtitle("Median IBU by State") +
    theme_minimal() +
    theme(legend.position = "none")

# Q5: Which state has the maximum alcoholic (ABV) beer? Which state has the
# most bitter (IBU) beer?
## Max ABV State
brew_beers_new %>%
    group_by(State) %>%
    filter(!is.na(ABV)) %>%
    summarize(max_abv = max(ABV)) %>%
    slice_max(max_abv, n = 1)

## Max IBU State
brew_beers_new %>%
    group_by(State) %>%
    filter(!is.na(IBU)) %>%
    summarize(max_ibu = max(IBU)) %>%
    slice_max(max_ibu, n = 1)

# Q6: Comment on the summary statistics and distribution of the ABV variable.
brew_beers_new %>%
    select(ABV) %>%
    filter(!is.na(ABV)) %>%
    summary(ABV)

## ABV Boxplot
brew_beers_new %>%
    filter(!is.na(ABV)) %>%
    ggplot(aes(y = ABV)) +
    geom_boxplot(fill = "#3a3aa5dc") +
    ylab("ABV") +
    ggtitle("ABV Boxplot") +
    theme_minimal()

## ABV Histgram
brew_beers_new %>%
    filter(!is.na(ABV)) %>%
    ggplot(aes(x = ABV)) +
    geom_histogram(fill = "#3a3aa5dc") +
    xlab("ABV") +
    ylab("Count") +
    ggtitle("ABV Histogram") +
    theme_minimal()

# Q7: Is there an apparent relationship between the bitterness of the beer and
# its alcoholic content? Draw a scatter plot.  Make your best judgment of a
# relationship and EXPLAIN your answer.
brew_beers_new %>%
    filter(!is.na(ABV) & !is.na(IBU)) %>%
    ggplot(aes(x = ABV, y = IBU)) +
    geom_point() +
    geom_smooth() +
    xlab("ABV") +
    ylab("IBU") +
    ggtitle("ABV vs. IBU") +
    theme_minimal()

brew_beers_new %>%
    filter(!is.na(ABV) & !is.na(IBU)) %>%
    ggplot(aes(x = IBU, y = ABV)) +
    geom_point() +
    geom_smooth() +
    xlab("IBU") +
    ylab("ABV") +
    ggtitle("IBU vs. ABV") +
    theme_minimal()

## Restrictin ABV between Q1-Q3
brew_beers_new %>%
    filter(!is.na(ABV) & !is.na(IBU)) %>%
    filter(between(ABV, .05, .067)) %>%
    ggplot(aes(x = ABV, y = IBU)) +
    geom_point() +
    geom_smooth() +
    xlab("ABV") +
    ylab("IBU") +
    ggtitle("IBU vs. ABV Limited to ABV: Q1-Q3") +
    theme_minimal()

## It appears there is a fairly tight positive relationship bewtween the 1st
## and 3rd Quartile of ABV. The relationship weakens greatly towards the upper
## and lower limits of ABV

# Q8: Budweiser would also like to investigate the difference with respect to
# IBU and ABV between IPAs (India Pale Ales) and other types of Ale
# (any beer with “Ale” in its name other than IPA).  You decide to use KNN
# classification to investigate this relationship.  Provide statistical
# evidence one way or the other. You can of course assume your audience is
# comfortable with percentages… KNN is very easy to understand conceptually.
# In addition, while you have decided to use KNN to investigate this
# relationship (KNN is required) you may also feel free to supplement your
# response to this question with any other methods or techniques you have
# learned.  Creativity and alternative solutions are always encouraged.

# Q9: Knock their socks off!  Find one other useful inference from the data
# that you feel Budweiser may be able to find value in.  You must convince
# them why it is important and back up your conviction with appropriate
# statistical evidence.
```

# EDA
```{r}

# Map of Breweries by State
map_brews <- left_join(mapdata, brew_beers_summary)
head(map_brews)
map_brews[5000, ] # testing random line

map_brews %>%
    ggplot(aes(long, lat, group = subregion)) +
    geom_map(
        aes(map_id = region),
        map = mapdata,
        color = "gray80", fill = "gray 30", size = 0.3
    ) +
    coord_map("ortho", orientation = c(39, -98, 0)) +
    geom_polygon(aes(group = group, fill = count), color = "black") +
    ggtitle("State Heat Map - Brewery Count") +
    scale_fill_scico(palette = "bilbao") +
    theme_minimal()

# EDA
brew_beers_new %>%
    filter(!is.na(ibu_cat) & !is.na(abv_cat)) %>%
    ggplot(aes(x = ibu_cat_num, fill = style_strict)) +
    geom_bar() +
    facet_wrap(~abv_cat_num, nrow = 1) +
    xlab("IBU Category") +
    ggtitle("IBU Category by ABV Facet Wrap and Style") +
    theme_minimal()



brew_beers_new %>%
    filter(!is.na(ibu_cat) & !is.na(abv_cat)) %>%
    ggplot(aes(x = ABV, y = IBU)) +
    geom_point() +
    facet_grid(abv_cat_num~ibu_cat_num) +
    xlab("ABV Cat") +
    ylab("IBU Cat")
# Beer count has a positive relation with ABV and IBU until category 2 of ABV
# It appears that at higher ABVs there is a negative coorelation between ABV
# and IBU

## ABV vs. IBU by Style
brew_beers_new %>%
    filter(!is.na(ibu_cat) & !is.na(abv_cat)) %>%
    ggplot(aes(x = ABV, y = IBU)) +
    geom_point(aes(color = style_strict)) +
    geom_smooth() +
    facet_wrap(~style_strict) +
    ggtitle("ABV vs IBU - Style Facet Wrap")

brew_beers_new %>%
    filter(!is.na(ibu_cat) & !is.na(abv_cat)) %>%
    ggplot(aes(x = IBU, y = ABV)) +
    geom_point(aes(color = style_strict)) +
    geom_smooth() +
    facet_wrap(~style_strict) +
    ggtitle("IBU vs ABV - Style Facet Wrap")

## Top style by State
top_beer <- brew_beers_new %>%
    filter(!is.na(ibu_cat) & !is.na(abv_cat)) %>%
    group_by(State, style_strict) %>%
    summarize(count = n())

top_beer %>%
    ggplot(aes(x = reorder(State, -count), y = count, fill = style_strict)) +
    geom_bar(stat = "identity") +
    xlab("State") +
    ylab("Count") +
    ggtitle("Beer Styles by State") +
    theme_minimal()

sorted_group <- top_beer[order(top_beer$State, -top_beer$count), ]
top_style_by_state <- sorted_group[!duplicated(sorted_group$State), ]

top_style_by_state %>%
    ggplot(aes(x = reorder(State, -count), y = count, fill = style_strict)) +
    geom_bar(stat = "identity") +
    xlab("State") +
    ylab("Count") +
    ggtitle("Top Style by State") +
    theme_minimal()

brew_beers_new %>%
    group_by(style_strict) %>%
    summarize(count = n())

## Top n Cities ranked by Brewery count
top_city <- brew_beers_new %>%
    group_by(City, brewery_name) %>%
    summarize(count = n())

sorted_group2 <- top_city[order(top_city$City, -top_city$count), ]
top_city_by_brewery <- sorted_group2[!duplicated(sorted_group2$City), ]

t <- brew_beers_new %>%
    group_by(City, brewery_name) %>%
    summarize(count = n()) %>%
    select(City, count) %>%
    slice_max(count, n = 20) %>%
    ggplot(aes(x = reorder(City, -count), y = count, fill = City)) +
    geom_bar(stat = "identity") +
    xlab("City") +
    ylab("Brewery Count") +
    ggtitle("Cities with most Breweries") +
    theme_minimal() +
    theme(legend.position = "none")


brew_beers_new %>%
    filter(!is.na(ABV) & !is.na(IBU) & State == " UT") %>%
    ggplot(aes(x = IBU, y = ABV)) +
    geom_point() +
    geom_smooth() +
    xlab("IBU") +
    ylab("ABV") +
    ggtitle("Utah - IBU vs. ABV") +
    theme_minimal()

```


# Beer Advocate Styles
```{r}
# Beer Advocate Styles
beer_advocate_styles <- "https://www.beeradvocate.com/beer/styles/"
## Check scraping permissions
paths_allowed(paths = c(beer_advocate_styles))

# Return Data
beer_advocate <- read_html(beer_advocate_styles)

# Get Style Family Length for for loop
style_family_length <-
    beer_advocate %>%
    html_nodes("#ba-content b") %>%
    html_text2()
style_family_length
style_length <- length(style_family_length)

# Blank dataframe for for loop
style_df_ba <- data.frame(style = c(), style_family = c())

# Retrieve Style Family and Style then create data frame from list
for (i in 1:style_length) {
    # Pull each Style Family y
    style_family_node <- paste0(".stylebreak:nth-child(", i, ") b")
    style_family <-
        beer_advocate %>%
        html_nodes(style_family_node) %>%
        html_text2
    style_family

    # Pull each Style and convert to dataframe
    style_node <- paste0("#ba-content .stylebreak:nth-child(", i, ") li")
    style <-
        beer_advocate %>%
        html_nodes(style_node) %>%
        html_text2()

    style_df <- as.data.frame(style)
    # Assign Style family to each line of data frame
    style_df$style_family <- style_family
    # Append data frame onto final style dataframe
    style_df_ba <- rbind(style_df_ba, style_df)
}

# Reorder dataframe
style_df_ba <- style_df_ba[, c(2, 1)]
style_df_ba
view(style_df_ba)
# Write to csv
write.csv(style_df_ba, file = "ba_style_guide.csv")
```
